### ISSUE TITLE
[QUESTION]simulator?

### ISSUE THREAD

**Issue by zychaoqun** [MIT-SPARK/Hydra#13]
hi, what simulator is used in the testing? Thanks!

**Comment by nathanhhughes** [comment]
Hi, thank you for your interest in our work! You can find more details in our paper [here](http://www.roboticsproceedings.org/rss18/p050.pdf), but we used the uHumans2 dataset to provide simulated data for our experiments, which can be found on the SparkLab's website [here](http://web.mit.edu/sparklab/datasets/uHumans2/). The unity simulator that was used to produce the uHumans2 dataset is [TESSE](https://github.com/MIT-TESSE).
