### ISSUE TITLE
How to run Hydra using Zed Camera 

### ISSUE THREAD

**Issue by MVPramod** [MIT-SPARK/Hydra#21]
Hi Nathan

I am trying to run Hydra using zed camera can you help me out with the procedure and i am not an MIT student i need to know what is alternative package for semantic_recolor.

**Comment by nathanhhughes** [comment]
Hi, thanks for your interest in our work! Please see issue #1 for an in-depth discussion on how to replace the functionality of semantic_recolor (as well as efforts by someone else in trying to set up Hydra with a Zed2i camera).

**Comment by nathanhhughes** [comment]
Closing this for now (please use #1 for any questions unless you run into a specific problem that isn't appropriate to discuss in that issue).
