### ISSUE TITLE
how to run own dataset

### ISSUE THREAD

**Issue by banovers** [MIT-SPARK/Hydra#23]
hi
Excuse me,if I run my own dataset, how do I need to modify the dataset to obtain DSG,or use 2D semantic segmentation to achieve.

**Comment by nathanhhughes** [comment]
Hi, thanks for your interest in our work (and sorry for the delay). Please see #1 for a detailed discussion of how to run Hydra on a different dataset.  I'm going to close this for now, please use #1 for any generic questions (feel free to re-open this issue if there ends up being a specific bug or question that wouldn't be beneficial to the discussion in #1).
