### ISSUE TITLE
Protobuf Compiler dependency

### ISSUE THREAD

**Issue by ltstein** [MIT-SPARK/Hydra#3]
Very interesting work. I tried to test this out using the `osrf/ros:noetic-desktop` docker image. After installing git, the mentioned dependencies and setting up the workspace according to the instructions, when trying to build I ran into the following error:
`Protobuf compiler version doesn't match library version 3.6.1` in voxblox. 
Searching around a bit, I found the error message was incomplete due to not having protobuf compiler installed. 
After installing `sudo apt install protobuf-compiler`, cleaning up the build and rebuilding everything succeeded.

**Comment by nathanhhughes** [comment]
Thanks, and good catch! Not sure how that got pulled in on my systems, but I've updated the readme to include explicitly installing it along with `libprotobuf-dev`
