### ISSUE TITLE
how to save compressed models or data

### ISSUE THREAD

**Issue by banovers** [MIT-SPARK/Hydra#32]
Hello, I have successfully built Hydra. May I ask how to save compressed models or data?

**Comment by nathanhhughes** [comment]
@BavanthaU Thanks for helping out with the issue, you are correct! Hydra will save related outputs to the specified path (provided the right directories are there) when it exits.

I've seen ROS kill Hydra before it manages to save out everything if you just use `ctrl-C` to terminate the launch file on slower machines, so you may want to run with:
```
roslaunch hydra_ros uhumans2.launch exit_mode:=SERVICE
```
which lets you call
```
rosservice call /hydra_ros_node/shutdown "{}"
```
to shutdown hydra without running into issues with ROS killing it prematurely.
