### ISSUE TITLE
[QUESTION] How to visualize json file data?

### ISSUE THREAD

**Issue by adam-muk** [MIT-SPARK/Hydra#35]
Hi,

What is the best tool to visualize the dsg.json file?

**Comment by nathanhhughes** [comment]
You can use [this](https://github.com/MIT-SPARK/Hydra-ROS/blob/main/hydra_ros/launch/utils/hydra_visualizer.launch) launch file to visualize a saved scene graph, which looks something like:
```
roslaunch hydra_ros hydra_visualizer.launch scene_graph_dir:=/path/to/scene/graph scene_graph:=dsg.json
```
for the path `/path/to/scene/graph/dsg.json`.

Alternatively, if you have the python bindings for [Spark-DSG](https://github.mit.edu/SPARK/Spark-DSG) installed, you can call [this](https://github.mit.edu/SPARK/Spark-DSG/blob/bf44ced2ffd945bd34cc8a2882d31e44f2b8a7b6/python/src/spark_dsg/open3d_visualization.py#L396) function on a loaded scene graph to visualize in open3d. The open3d visualization is less fully featured than the ros/rviz based one that the launch file starts.
