### ISSUE TITLE
Room classification [QUESTION]

### ISSUE THREAD

**Issue by JiaheXu** [MIT-SPARK/Hydra#38]
Hi Hydra developers,

This is a very exciting work!!! I am curious about the room classification method you are using in Hydra, but I am not sure which part of the code is is on it. Can you please send me the link to that part? Thanks!!!

**Comment by nathanhhughes** [comment]
Thank you for your interest in our work! We are still working on releasing the room classification code (see [here](https://github.com/MIT-SPARK/Hydra#news)), which I hope to have out soon.

**Comment by nathanhhughes** [comment]
Sorry for the delay in releasing the code, it is now available here: https://github.com/MIT-SPARK/Hydra-GNN
