### ISSUE TITLE
a build problem

### ISSUE THREAD

**Issue by cleMentines0** [MIT-SPARK/Hydra#41]
When I execute "catkin build hydra", I get:

Errors     << hydra:check /home/ty/桌面/hy/Hydra/catkin_ws/logs/hydra/build.check.005.log
CMake Warning at /opt/ros/melodic/share/catkin/cmake/catkin_package.cmake:166 (message):
  catkin_package() DEPENDS on 'spark_dsg' but neither
  'spark_dsg_INCLUDE_DIRS' nor 'spark_dsg_LIBRARIES' is defined.
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  CMakeLists.txt:57 (catkin_package)

You have called ADD_LIBRARY for library hydra without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at /home/ty/桌面/hy/Hydra/catkin_ws/src/hydra/CMakeLists.txt:68 (add_library):
  Target "hydra" links to target "teaserpp::teaser_registration" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at /home/ty/桌面/hy/Hydra/catkin_ws/src/hydra/CMakeLists.txt:68 (add_library):
  Target "hydra" links to target "spark_dsg::spark_dsg" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at /opt/ros/melodic/share/catkin/cmake/test/gtest.cmake:180 (add_executable):
  Target "test_hydra" links to target "teaserpp::teaser_registration" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/test/gtest.cmake:89 (_catkin_add_executable_with_google_test)
  /opt/ros/melodic/share/catkin/cmake/test/gtest.cmake:37 (_catkin_add_google_test)
  tests/CMakeLists.txt:1 (catkin_add_gtest)

CMake Error at /opt/ros/melodic/share/catkin/cmake/test/gtest.cmake:180 (add_executable):
  Target "test_hydra" links to target "spark_dsg::spark_dsg" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/test/gtest.cmake:89 (_catkin_add_executable_with_google_test)
  /opt/ros/melodic/share/catkin/cmake/test/gtest.cmake:37 (_catkin_add_google_test)
  tests/CMakeLists.txt:1 (catkin_add_gtest)

make: *** [cmake_check_build_system] Error 1
cd /home/ty/桌面/hy/Hydra/catkin_ws/build/hydra; catkin build --get-env hydra | catkin env -si  /usr/bin/make cmake_check_build_system; cd -

I have checked the CMakeLists.txt file and I think there is nothing wrong with it.
Can you help me deduce what's wrong there?
This is my first time trying to reproduce the code, thanks for answering my question.

**Comment by cleMentines0** [comment]
(Sorry, this is just a compilation issue, not a bug report. Didn't mean to add the bug label...)

**Comment by cleMentines0** [comment]
on Ubuntu 18.04

**Comment by nathanhhughes** [comment]
Thanks for your interest in our work (and don't worry about the bug label, it's intentionally added automatically :smile:)! Please do note that we no longer support Ubuntu 18.04 (given that it is end of life). It *should* still build (but our private version of Hydra no longer does, and we plan on releasing more updates soon).  

That said, I'm not sure what's going on with your system. What does your catkin workspace look like? Running `vcs import . < hydra/install/hydra.rosinstall` from the build instructions [here](https://github.com/MIT-SPARK/Hydra#building-hydra) should make sure that both `spark_dsg` and `teaserpp` should be built before Hydra (and that they should be found when Hydra is building).

**Comment by cleMentines0** [comment]
sorry, I tried running catkin build again but got different results.
I am remotely controlling other people’s computers to run programs.
thanks for answering my question.

![{Z$~B P~BGR3PQJJV4J651H](https://github.com/MIT-SPARK/Hydra/assets/103505554/63bcd5dd-50ac-47bb-9c16-76dd2d39e660)
![%Q 6{DNU40A}R3)NYZ70Y Y](https://github.com/MIT-SPARK/Hydra/assets/103505554/3234a2e5-2f74-40d3-bcab-05e96f3e01a4)

**Comment by nathanhhughes** [comment]
Please make sure all the dependencies of Hydra have the correct branches and are up to date, i.e., that they match the versions [here](https://github.com/MIT-SPARK/Hydra/blob/main/install/hydra.rosinstall). For example, it looks both `kimera_semantics` and `voxblox` are the wrong version. 

A helpful tool for this would be to run `vcs branch src` from the top-level directory of the catkin workspace.

**Comment by cleMentines0** [comment]
thank you, it works

**Comment by nathanhhughes** [comment]
Great! Glad it worked out. I'm going to close this, feel free to reopen (or start a new issue) if anything else pops up!
