### ISSUE TITLE
[QUESTION] 2D Semantic segmentation

### ISSUE THREAD

**Issue by drawdehe** [MIT-SPARK/Hydra#43]
Regarding setting up a 2D semantic segmentation for use with Hydra (and Kimera-Semantics) that you wrote about [here](https://github.com/MIT-SPARK/Hydra/issues/1#issuecomment-1171277361), have you released any code related to this? Or do you have any other pointers for setting it up? I am trying to do 2D semantic segmentation of recorded data from an intel realsense d435i device. 

Thank you!

**Comment by nathanhhughes** [comment]
Hi @drawdehe, thanks for your interest in our work! We have unfortunately not been able to release our semantic segmentation approach, and #1 still is the best guide as to what Hydra expects as input. I'm currently working on another release of Hydra that hopefully will have more straightforward support for custom datasets (the timeline for that release is currently a month or so)
