### ISSUE TITLE
[QUESTION] About Hydra-multi

### ISSUE THREAD

**Issue by kajo-kurisu** [MIT-SPARK/Hydra#45]
Great work ! I notice that ur latest work Hydra-multi has been published in IROS and i wonder if u prefer to open source!

**Comment by yunzc** [comment]
Hi @kajo-kurisu we do plan on open sourcing the Hydra-Multi pipeline, but not in the near future. Thank you for your interest in our work!

**Comment by salvaba94** [comment]
Hi, also amazed by this work. Any updates on the open sourcing of the multi extension?

**Comment by friendship1** [comment]
Hi, I'm also interested in Hydra-multi. Any updates?
