### ISSUE TITLE
[QUESTION]vcs import . < hydra/install/hydra.rosinstall    ---There is no file or directory for that

### ISSUE THREAD

**Issue by 1075717581** [MIT-SPARK/Hydra#47]
I am very interested in your project, but I am just a beginner and cannot run through the program according to readme. Could you please answer this question for me?
vcs import . < hydra/install/hydra.rosinstall
bash: hydra/install/hydra.rosinstall: There is no file or directory for that

**Comment by nathanhhughes** [comment]
Hi, thank you for your interest in our work! Please make sure that Hydra cloned successfully in the step before the `vcs import` command. That said, it may be helpful to familiarize yourself with the linux command line and git before diving into the instructions!
