### ISSUE TITLE
Error building hydra

### ISSUE THREAD

**Issue by kayodeadewole** [MIT-SPARK/Hydra#49]
I am having the error below when building hydra. About 23 out of 25 packages succeeded. I don't know what I have done wrong. I am running Ubuntu 20.04 on UTM as VM.

<img width="732" alt="Screenshot 2024-04-03 at 08 27 34" src="https://github.com/MIT-SPARK/Hydra/assets/94366721/d8053a3a-6910-41e8-8046-0b9b14324895">

**Comment by nathanhhughes** [comment]
Hi, thanks for your interest in our work! The issue that you were seeing was that the GNN-based loop closure detection code was enabled by default (via the CMake option `HYDRA_ENABLE_GNN`) which was only available for x86 architectures (and it appears that you are building on arm or another architecture). Our latest release turns off this feature by default and the code should build now
