### ISSUE TITLE
[QUESTION] Access To Matterport3D dataset

### ISSUE THREAD

**Issue by LeonGoretzkatju** [MIT-SPARK/Hydra#50]
Hello!

Thank you so much for your wonderful work, I really learned a lot from your open-sourced project, now I want to run Hydra in Vision-Language-Navigation dataset (Matterport3D), and I noticed that in your IJRR paper, you mentioned that you have used the MP3D for generating Scene Graph for different scenes, which is shown as follows,
![Screenshot from 2024-04-27 15-27-04](https://github.com/MIT-SPARK/Hydra/assets/53984646/51169025-2dc2-45a7-9045-0303cca2d126)
And I also find the MP3D-related launch and .yaml configuration file in your open-sourced Hydra code, so the question I want to ask you, is that can you provide the relevant toolbox to make Habitat Simulator compatible with ROS system, or some batch-processing program file to make habitat-sim work with ROS, if possible, could you please share the MP3D rosbag public? Thank you so much!
I'm waiting for your reply, Thank you so much!

**Comment by nathanhhughes** [comment]
Hi, thanks for your interest in our work! With our recent release, we've included the python bindings and habitat interface for running with MP3D, which can be found [here](https://github.com/MIT-SPARK/Hydra/tree/main/python). Please note that this interface is not the most stable, so there may be issues.
