### ISSUE TITLE
[QUESTION] Inquiry About Dockerfile Availability for Running Demo

### ISSUE THREAD

**Issue by ertyu116-116** [MIT-SPARK/Hydra#57]
Thank you for this great work! I believe this work is a breakthrough in the SLAM research field.

I have a small question: is there any Dockerfile to run the demo?

**Comment by nathanhhughes** [comment]
Thanks for your interest in our work! There is currently no docker file for running the demo. We would welcome (clean and well-designed) contributions in that vein!

**Comment by Inoriros** [comment]
I have built a Docker container based on the osrf/ros image. My container has successfully run the Hydra demo and its Python bindings on my Ubuntu 22.04 system equipped with an NVIDIA 3090. I have not yet published it to Docker Hub because it includes Hydra.
